expenses/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .views import *

app_name = 'expenses'

urlpatterns = [
    
    # Regular URLs
    url(r'^daily-expenses/$', daily_expenses_view, name='daily_expenses_view'),
    url(r'^expense-archive/$', expense_archive_list, name='expense_archive_list'),
    url(r'^expense-archive/(?P<pk>[0-9]+)/$', expense_archive_detail, name='expense_archive_detail'),
    
    # Ajax URLs
    url(r'ajax/create-expense/$', create_expense),
    url(r'ajax/delete-expense/$', delete_expense),
    
    url(r'ajax/filter-expenses/$', filter_expenses),
    url(r'ajax/close-account/$', close_account)
]

main/urls.py
from django.conf.urls import url
from .views import *

app_name = 'main'

urlpatterns = [

    # HTTP URLs
    url(r'^$', todays_orders),
    url(r'^new-order/$', new_order),
    url(r'^menu/', menu_view),
    url(r'order-menu/$', order_menu),

    # AJAX URLs
    url(r'^ajax/add-client/$', add_client),
    url(r'^ajax/remove-order/$', remove_order),
    url(r'^ajax/inquire-client/$', inquire_client),
    url(r'^ajax/create-order/$', create_order),

]

restaurant_app/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^', include('main.urls')),
    url(r'^', include('accounts.urls')),
    url(r'^expenses/', include('expenses.urls')),
    url(r'^admin/', admin.site.urls),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

expenses/models.py
from django.db import models
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver
from django.conf import settings

import pendulum


from abstract.models import TimeStampedModel, App


class Expense(TimeStampedModel):
    
    description = models.CharField(max_length=300)
    balance_change = models.FloatField(default=0.0)
    total_after_change = models.FloatField(null=True, blank=True)
    
    date = models.DateField()
    
    def update_total_after_change(self, new_balance_change):
        
        self.total_after_change += -self.balance_change
                
        self.balance_change = new_balance_change
        self.total_after_change += new_balance_change
        
        self.save()
        
    def get_new_totals(self, old_balance_change):
        
        expenses = Expense.objects.filter(created__gt=self.created)
        
        totals = {
            self.id: self.total_after_change
        }
        
        for index, expense in enumerate(expenses):
            
            expense.total_after_change += self.balance_change - old_balance_change
            expense.save()
            
            totals[expense.id] = expense.total_after_change
            
            if index == expenses.count() - 1:
                
                app = App.objects.first()
                
                app.current_balance = expense.total_after_change
                app.save()
            
        return totals
    
    @property
    def formatted_balance_change(self):
        
        if self.balance_change < 0:
            return -1 * self.balance_change
        
        return self.balance_change
    
    def as_dict(self):
        
        data = {
            'id': self.id,
            'description': self.description,
            'balance_change': self.balance_change,
            'formatted_balance_change': self.formatted_balance_change,
            'total_after_change': self.total_after_change,
            'created': self.created.astimezone(pendulum.timezone(settings.TIME_ZONE)).strftime('%d/%m/%Y %I:%M %p')
        }
        
        return data
    
    def as_post_data_dict(self):
        
        return {
            'description': self.description,
            'balance_change': self.balance_change if self.balance_change > 0 else -self.balance_change
        }


class DailyExpense(TimeStampedModel):
    
    opening_balance = models.FloatField(null=True, blank=True)
    closing_balance = models.FloatField(null=True, blank=True)
    
    closed = models.BooleanField(default=False)
    date = models.DateField()
    closing_time = models.DateTimeField(null=True, blank=True)
    
    def __str__(self):
        
        return str(self.date)
    
    def as_dict(self, **kwargs):
        
        data = {
            'id': self.id,
            'opening_balance': self.opening_balance,
            'closing_balance': self.closing_balance,
            'date': self.date.strftime('%d/%m/%Y'),
            
            'closed': self.closed
        }
        
        if kwargs.get('include_closing_data', False):
            
            closing_data = {
                'total_revenue': self.total_revenue,
                'total_expenses': self.total_expenses,
                'closing_time': self.closing_time.astimezone(pendulum.timezone(settings.TIME_ZONE)).strftime('%d/%m/%Y %I:%M %p') if self.closing_time else None
            }
            
            data.update(closing_data)
            
        if kwargs.get('include_expenses', False):
            
            data['expenses'] = [expense.as_dict() for expense in Expense.objects.filter(date=self.date)]
        
        return data
    
    @property
    def total_revenue(self):
        
        expenses = Expense.objects.filter(date=self.date)
        
        if expenses.exists():
            total_revenue = sum([expense.balance_change for expense in expenses if expense.balance_change > 0] or [0,])
            
            return float(total_revenue)
        
        return 0
        
    @property
    def total_expenses(self):
        
        expenses = Expense.objects.filter(date=self.date)
        
        if expenses.exists():
            total_expenses = -sum([expense.balance_change for expense in expenses if expense.balance_change < 0] or [0,])
            
            return float(total_expenses)
        
        return 0

expenses/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.utils import timezone
from django.views.decorators.csrf import csrf_exempt

from abstract.utils import get_date_filters, get_abstract_data

from accounts.utils import prepare_post_data
from . import utils
from .models import *


import requests

def daily_expenses_view(request):
    
    data = get_abstract_data(view='daily-expenses')
    
    utils.close_old_days()
    
    data['expenses'] = Expense.objects.filter(date=timezone.now().date())
    
    return render(request, 'expenses/daily-expenses.html', context=data)

def expense_archive_list(request):
    
    data = get_abstract_data()
    
    data['daily_expenses'] = DailyExpense.objects.exclude(date=timezone.now().date())
    
    return render(request, 'expenses/expense-archive-list.html', context=data)

def expense_archive_detail(request, pk):
    
    data = get_abstract_data()
    
    expense = DailyExpense.objects.get(pk=pk)
    
    data['daily_expense'] = expense.as_dict(include_closing_data=True, include_expenses=True)

    return render(request, 'expenses/expense-archive-detail.html', context=data)

@csrf_exempt
def create_expense(request):
    
    if request.is_ajax():
        
        data = request.POST
        
        description = data['description']
        balance_change = float(data['balanceChange'])
        
        expense_obj = Expense.objects.create(
            description=description,
            balance_change=balance_change,
            date=timezone.now().date()
        )
        
        app = App.objects.first()
        
        app.current_balance += balance_change
        app.save()
        
        expense_obj.total_after_change = app.current_balance
        expense_obj.save()
        
        post_data = prepare_post_data()
        
        requests.post('https://qwepoiasdkljxcmv.herokuapp.com/TheDistro/post-data/', data=post_data)
        
        return JsonResponse({
            'expense': expense_obj.as_dict(),
            'current_balance': app.current_balance,
            'data': post_data
        })
    
def delete_expense(request):
    
    if request.is_ajax():
        
        expense = Expense.objects.get(pk=request.GET['pk'])
        
        app = App.objects.first()
    
        expenses = Expense.objects.filter(created__gt=expense.created)

        totals = {}
        
        if expenses.exists():
            for index, exp in enumerate(expenses):

                exp.total_after_change -= expense.balance_change
                exp.save()

                totals[exp.id] =  exp.total_after_change

                if index == expenses.count() - 1:

                    app.current_balance = exp.total_after_change
                    app.save()
                    
        else:
            
            app.current_balance -= expense.balance_change
            app.save()
        
        expense.delete()
        
        post_data = prepare_post_data()
        requests.post('https://qwepoiasdkljxcmv.herokuapp.com/TheDistro/post-data/', data=post_data)
        
        return JsonResponse({
            'totals': totals,
            'current_balance': app.current_balance,
            'data': post_data
        })

@csrf_exempt
def filter_expenses(request):
    
    if request.is_ajax():
        
        data = request.POST
        
        balance_change = data['balanceChange']
        description = data['description']
        from_ = data['from']
        to = data['to']
        total = data['total']
        
        all_expenses = Expense.objects.all()
        
        if balance_change:
            balance_change = float(balance_change)
            
            balance_filter = all_expenses.filter(balance_change=balance_change)
            
        else:
            balance_filter = all_expenses
            
        if description:
            description_filter = all_expenses.filter(description=description)
            
        else:
            description_filter = all_expenses
            
        date_filter = get_date_filters(from_, to, 'created__range', all_expenses, format_='%d/%m/%Y %I:%M %p')
        
        if total:
            total = float(total)
            
            total_filter = all_expenses.filter(total_after_change=total)
            
        else:
            total_filter = all_expenses
            
        all_expenses = set(all_expenses)
        
        all_filters = [
            
            balance_filter,
            description_filter,
            date_filter,
            total_filter
            
        ]
        
        all_filters = [frozenset(qs) for qs in all_filters]
        
        all_filters = list(all_expenses.intersection(*all_filters))
        
        all_filters.sort(key=lambda expense: expense.created)
        
        all_filters = [expense.as_dict() for expense in all_filters]
        
        return JsonResponse({
            'expenses': all_filters
        })
    
def close_account(request):
    
    if request.is_ajax():
        
        daily_expense = DailyExpense.objects.get(date=timezone.now().date())
        
        app = App.objects.first()
        
        daily_expense.closing_balance = app.current_balance
        daily_expense.closing_time = timezone.now()
        daily_expense.closed = True
        daily_expense.save()
        
        return JsonResponse(daily_expense.as_dict(include_closing_data=True))
    

expenses/templates/expenses/daily-expenses.html
{% extends 'expenses/expenses-base.html' %}
{% load static %}

{% block Title %}مصاريف اليوم{% endblock %}

{% block table_id %}daily-expenses-table{% endblock %}
{% block table_attrs %}data-item-type='expense'{% endblock %}

{% block extra_headers %}<th>حذف</th>{% endblock %}

{% block rows %}

    {% for expense in expenses %}
    <tr data-pk="{{ expense.pk }}">
        <td></td>
        <td>{{ forloop.counter }}</td>
        {% if expense.balance_change < 0 %}
        <td class="editable-locked expense-td" data-field-name="formatted_balance_change" data-input-type="number" data-sign="-">{{ expense.formatted_balance_change }}</td>
        <td class="editable-locked revenue-td" data-field-name="formatted_balance_change" data-input-type="number" data-sign="+"></td>
        
        {% else %}
        <td class="editable-locked expense-td" data-field-name="formatted_balance_change" data-input-type="number" data-sign="-"></td>
        <td class="editable-locked revenue-td" data-field-name="formatted_balance_change" data-input-type="number" data-sign="+">{{ expense.formatted_balance_change }}</td>
        {% endif %}
        
        <td class="editable-locked" data-field-name="description" data-input-type="text">{{ expense.description }}</td>
        <td dir="ltr">{{ expense.created|date:"d/m/Y h:i A" }}</td>
        <td class="editable-locked" data-field-name="total_after_change" data-input-type="number">{{ expense.total_after_change }}</td>
        <td><img src="{% static 'images/remove.png' %}" class="icon remove-expense-item" data-pk="{{ expense.pk }}"></td>
        
    </tr>
    {% endfor %}
    
    <tr>
        <td></td>
        <td></td>
        <td class="editable-locked empty expense-td" data-field-name="formatted_balance_change" data-sign="-" data-input-type="text" style="height:38px" contenteditable="true"></td>
        <td class="editable-locked empty revenue-td" data-field-name="formatted_balance_change" data-sign="+" data-input-type="text" contenteditable="true"></td>
        <td class="editable-locked empty" data-field-name="description" data-input-type="text" contenteditable="true"></td>
        <td data-field-name="created" dir="ltr"></td>
        <td class="editable-locked empty" data-field-name="total_after_change"></td>
        <td></td>
    </tr>
    
{% endblock %}

{% block extra %}
<table id="todays-closing-table" class="table table-bordered" dir="rtl" style="{% if not daily_expense.closed %}display:none{% endif %}">
    
    <thead style="text-align:center">
        <tr>
            <th>اجمالى السحب</th>
            <th>اجمالى الاضافة</th>
            <th>الوقت</th>
            <th>الاجمالى</th>
        </tr>
    </thead>
    
    
    <tbody>
        <tr>
            {% if daily_expense.closed %}
            <td id="todays-total-expenses" class="expense-td">{{ daily_expense.total_expenses }}</td>
            <td id="todays-total-revenue" class="revenue-td">{{ daily_expense.total_revenue }}</td>
            <td id="todays-closing-time">{{ daily_expense.closing_time }}</td>
            <td id="todays-closing-total">{{ daily_expense.closing_balance }}</td>
            {% else %}
            <td id="todays-total-expenses"></td>
            <td id="todays-total-revenue"></td>
            <td id="todays-closing-time"></td>
            <td id="todays-closing-total"></td>
            {% endif %}
        </tr>
    </tbody>
    
</table>
{% endblock %}

{% block js %}
    <script src="{% static 'expenses/js/daily-expenses.js' %}"></script>
{% endblock %}

expenses/templates/expenses/expense-archive-detail.html
{% extends 'expenses/expenses-base.html' %}
{% load static %}

{% block Title %}مصاريف يوم {% endblock %}

{% block table_id %}expense-archive-detail-table{% endblock %}




{% block rows %}

    {% for expense in daily_expense.expenses %}
    <tr data-pk="{{ expense.pk }}">
        
        <td></td>
        <td>{{ forloop.counter }}</td>
        {% if expense.balance_change < 0 %}
        <td class='expense-td' data-field-name="formatted_balance_change" data-input-type="number" data-sign="-">{{ expense.formatted_balance_change }}</td>
        <td class='revenue-td' data-field-name="formatted_balance_change" data-input-type="number" data-sign="+"></td>
        
        {% else %}
        <td class='expense-td' data-field-name="formatted_balance_change" data-input-type="number" data-sign="-"></td>
        <td class='revenue-td' data-field-name="formatted_balance_change" data-input-type="number" data-sign="+">{{ expense.formatted_balance_change }}</td>
        {% endif %}
        
        <td data-field-name="description" data-input-type="text">{{ expense.description }}</td>
        <td dir="ltr">{{ expense.created }}</td>
        <td data-field-name="total_after_change" data-input-type="number">{{ expense.total_after_change }}</td>
        
    </tr>
    {% endfor %}
{% endblock %}

{% block extra %}
    <table id="expense-archive-closing-table" class="table table-bordered" dir="rtl">

        <thead style="text-align:center">
            <tr>
                <th>اجمالى السحب</th>
                <th>اجمالى الاضافة</th>
                <th>الوقت</th>
                <th>الاجمالى</th>
            </tr>
        </thead>
        
        <tbody>
            <tr>
                <td id="expense-archive-total-expenses" class='expense-td'>{{ daily_expense.total_expenses }}</td>
                <td id="expense-archive-total-revenue" class='revenue-td'>{{ daily_expense.total_revenue }}</td>
                <td id="expense-archive-closing-time">{{ daily_expense.closing_time }}</td>
                <td id="expense-archive-closing-total">{{ daily_expense.closing_balance }}</td>
            </tr>
        </tbody>

    </table>
{% endblock %}

{% block js %}
    <script type="text/javascript">
        
        $('title').text($('title').text() + "{{ daily_expense.date }}");
        
        $('#expenses-submenu')
            .show()
            .children().children(':last').addClass('active');
        
        var currentView = 'expense-archive-detail',
            expenseDetailDate = "{{ daily_expense.date }}";
        
    </script>
{% endblock %}

expenses/templates/expenses/expense-archive-list.html
{% extends 'base.html' %}

{% block title %}أرشيف المصاريف{% endblock %}

{% block body %}
<table id="expense-archive-table" class="table table-bordered" dir="rtl">
    
    <thead style="text-align:center">
        <tr>
            <th>التاريخ</th>
            <th>العهدة أول اليوم</th>
            <th>العهدة اخر اليوم</th>
            <th>التفاصيل</th>
        </tr>
    </thead>
    
    <tbody>
        {% for expense in daily_expenses %}
        <tr data-pk="{{ expense.pk }}">
            <td>{{ expense.date|date:"d/m/Y" }}</td>
            <td>{{ expense.opening_balance }}</td>
            <td>{{ expense.closing_balance }}</td>
            <td><a href="{% url 'expenses:expense_archive_detail' expense.pk %}" class="expense-archive-detail-link">ذهاب</a></td>
        </tr>
        {% endfor %}
    </tbody>
    
</table>
{% endblock %}

{% block js %}
<script type="text/javascript">
    $('#expenses-submenu')
        .show()
        .children().children(':last').addClass('active');
</script>
{% endblock %}

expenses/templates/expenses/expenses-base.html
{% extends 'base.html' %}

{% block title %}{% block Title %}{% endblock %}{% endblock %}

{% block body %}
<table id="{% block table_id %}{% endblock %}" class="table table-bordered" dir="rtl" {% block table_attrs %}{% endblock %}>
    
    <thead style="text-align:center">
        <tr>
            <th></th>
            <th>م</th>
            <th>سحب</th>
            <th>اضافة</th>
            <th>البيان</th>
            <th>الوقت</th>
            <th>الاجمالى</th>
            {% block extra_headers %}{% endblock %}
            
        </tr>
    </thead>
    
    <tbody>
        {% block rows %}
        {% endblock %}
    </tbody>
    
</table>

{% block extra %}
{% endblock %}
{% endblock %}