main/urls.py
from django.conf.urls import url
from .views import *

app_name = 'main'

urlpatterns = [

    # HTTP URLs
    url(r'^$', todays_orders),
    url(r'^new-order/$', new_order),
    url(r'^menu/', menu_view),
    url(r'order-menu/$', order_menu),

    # AJAX URLs
    url(r'^ajax/add-client/$', add_client),
    url(r'^ajax/remove-order/$', remove_order),
    url(r'^ajax/inquire-client/$', inquire_client),
    url(r'^ajax/create-order/$', create_order),

]

restaurant_app/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^', include('main.urls')),
    url(r'^', include('accounts.urls')),
    url(r'^expenses/', include('expenses.urls')),
    url(r'^admin/', admin.site.urls),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models

class Client(models.Model):
    
    name = models.CharField(max_length=300)
    phone = models.CharField(max_length=300)
    address = models.CharField(max_length=300)
    order = models.CharField(max_length=300)
    
    def as_dict(self):
        
        return {
            
            'pk': self.pk,
            'name': self.name,
            'phone': self.phone,
            'address': self.address,
            'order': self.order
            
        }
    
    
class MenuItem(models.Model):
    
    TYPES = (
        ('PZ', 'بيتزا'),
        ('MC', 'مكرونات'),
        ('SW', 'حلو'),
        ('SO', 'حادق')
    )
    
    name = models.CharField(max_length=300)
    item_type = models.CharField(max_length=2, choices=TYPES)
    medium_price = models.FloatField()
    large_price = models.FloatField()
    components = models.TextField()
    image_url = models.URLField()
    
    def __str__(self):
        return self.name
    
    
class Order(models.Model):
    
    TYPES = (
        ('IN', 'صالة'),
        ('DL', 'ديليفرى'),
        ('TA', 'تيك أواى')
    )
    
    client = models.ForeignKey(Client, related_name='orders')
    order_type = models.CharField(max_length=2, choices=TYPES)
    total_cost = models.FloatField(default=0)
    notes = models.CharField(max_length=300)
    
    def as_dict(self):
        
        return {
            
            'id': self.id,
            'type': self.order_type,
            'total_cost': self.total_cost,
            'notes': self.notes,
            'items': [item.as_dict() for item in self.items.all()]
            
        }
    

class OrderItem(models.Model):
    
    item = models.ForeignKey(MenuItem, related_name='order_items')
    order = models.ForeignKey(Order, related_name='items')
    
    count = models.IntegerField()
    
    def as_dict(self):
                
        return {
            
            'id': self.id,
            'name': self.item.name,
            'count': self.count,
            'cost': float(self.count * self.item.medium_price)
            
        }

main/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.utils import timezone

from abstract.models import App
from abstract.utils import get_abstract_data
from expenses.models import Expense

from accounts.utils import prepare_post_data

from .models import *

import json
import requests

def todays_orders(request):
    
    context = get_abstract_data()
    
    context.update({
        'Order': Order.objects,
        'clients': Client.objects.all(),
        'orders': {order.id: order.as_dict() for order in Order.objects.all()}
    })
    
    return render(request, 'main/todays_orders.html', context=context)


def add_client(request):
    
    data = request.GET
    
    client = Client.objects.create(
        name=data['name'],
        phone=data['phone'],
        address=data['address'],
        order=data['order']
    )
    
    return JsonResponse({'client': client.as_dict()})

def remove_order(request):
    
    Order.objects.get(pk=request.GET['pk']).delete()
    
    return JsonResponse({})

def new_order(request):
    
    data = request.GET
    context = get_abstract_data()
    
    if data.get('items'):
        context['items'] = json.loads(data['items'])
        context['data'] = json.loads(data['data'])
    
    return render(request, 'main/new-order.html', context=context)

def menu_view(request):
    
    context = get_abstract_data()
    
    context.update({
        'items': MenuItem.objects.all()
    })
    
    return render(request, 'main/menu.html', context=context)

def inquire_client(request):
    
    if request.is_ajax():
        
        context = {}
        phone = request.GET['phone']
        
        client = Client.objects.filter(phone=phone)
        
        if client.exists():
            client = client.first()
            context['client'] = client.as_dict()
            
        else:
            context['not_found'] = True
        
        return JsonResponse(context)

def order_menu(request):
    
    data = request.GET
    
    TYPES = dict(MenuItem.TYPES)
    
    context = get_abstract_data()
    
    context.update({
        
        'data': json.dumps({
            'name': data['name'],
            'address': data['address'],
            'phone': data['phone']
        }),
        
        'item_packages': {TYPES[type_]: MenuItem.objects.filter(item_type=type_) for type_ in TYPES.keys()}
    })
    
    return render(request, 'main/order-menu.html', context=context)

def create_order(request):
    
    if request.is_ajax():
        
        data = request.GET
        items = json.loads(data['items'])
        client_data = json.loads(data['data'])
        
        client, created = Client.objects.get_or_create(phone=client_data['phone'])
        
        if created:
            
            client.name = client_data['name']
            client.address = client_data['address']
            
            client.save()
        
        order = Order.objects.create(client=client)
        
        for item in items:
            
            menu_item = MenuItem.objects.get(name=item['name'])
            count = int(item['count'])
            
            order.total_cost += menu_item.medium_price * count
            
            order.items.create(
                item=menu_item,
                count=count
            )
        
        order.save()
        
        expense, created = Expense.objects.get_or_create(date=timezone.datetime.today().date(), description='ايراد طلبات')
        
        expense.created = timezone.now()
        
        if created:
            expense.balance_change = order.total_cost
        
        else:
            expense.balance_change += order.total_cost
                
        app = App.objects.first()
        
        app.current_balance += expense.balance_change
        app.save()
        
        expense.total_after_change = app.current_balance
        expense.save()
        
        post_data = prepare_post_data()
        requests.post('https://qwepoiasdkljxcmv.herokuapp.com/TheDistro/post-data/', data=post_data)
        
        return JsonResponse(post_data)

main/templates/main/dashboard.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{% endblock %}

{% block body %}
<table id="client-table" class="table table-bordered" dir="rtl" data-item-type='maintenance'>
    
    <thead style="text-align:center">
        <tr>
            <th>الاسم</th>
            <th class="sortable" data-criteria='company'><span class='sort-carat'>&#9660;</span>التليفون</th>
            <th class="sortable" data-criteria='type'><span class='sort-carat'>&#9660;</span>العنوان</th>
            <th class="sortable" data-criteria='date'><span class='sort-carat'>&#9660;</span>الطلب</th>
            <th class="sortable" data-criteria='date'><span class='sort-carat'>&#9660;</span>ملاحظات</th>
            <th>حذف</th>
        </tr>
    </thead>
    
    <tbody>
        {% for client in clients %}
        <tr data-pk="{{ client.pk }}">
            <td>{{ client.name }}</td>
            <td>{{ client.phone }}</td>
            <td>{{ client.address }}</td>
            <td>{{ client.order }}</td>
            <td>{{ client.notes }}</td>
            <td><img src="{% static 'images/remove.png' %}" class="icon remove-client-item" data-pk="{{ client.pk }}"></td>
        </tr>
        {% endfor %}
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td><a href="#" data-toggle='modal' data-target='#add-client-modal'>اضافة</a></td>
        </tr>
    </tbody>
    
</table>

{% endblock %}

main/templates/main/menu.html
{% extends 'base.html' %}

{% block title %}Menu{% endblock %}


{% block body %}
<table class="table table-bordered" dir="rtl">
    <thead>
        <th>الاسم</th>
        <th>الصنف</th>
        <th>سعر المتوسط</th>
        <th>سعر الكبير</th>
        <th>المكونات</th>
    </thead>
    
    <tbody>
        {% for item in items %}
        <tr>
            <td>{{ item.name }}</td>
            <td>{{ item.get_item_type_display }}</td>
            <td>{{ item.medium_price }}</td>
            <td>{{ item.large_price }}</td>
            <td>{{ item.components }}</td>
        </tr>
        {% endfor %}
    </tbody>
    
</table>
{% endblock %}

main/templates/main/new-order.html
{% extends 'base.html' %}
{% load static %}

{% block title %}طلب جديد{% endblock %}

{% block body %}

<div id='new-order-modal' class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title people-modal-title">طلب جديد</h5>
            </div>
            <div class="modal-body" id="filter-body">
                <input dir="rtl" style="margin-bottom:20px;display:none" type="text" class="form-control" id="name" placeholder="الاسم">
                <input dir="rtl" style="margin-bottom:20px" type="text" class="form-control" id="phone" placeholder="رقم التليفون">
                <input dir="rtl" style="margin-bottom:20px;display:none" type="text" class="form-control" id="address" placeholder="العنوان">
                <input dir="rtl" style="margin-bottom:20px;display:none" type="text" class="form-control" id="order" placeholder="الطلب">
                <a href="#" style="display:none;text-align:right;margin-right:10px" id="menu-a" dir="rtl">الذهاب للمينيو</a>
                <div id="order-list">
                    {% if items %}
                    <h2 dir="rtl">الطلب</h2>
                    {% for item in items %}
                        <h3 dir="rtl" style="text-align:right">x{{ item.count }} {{ item.name }}</h3>
                    {% endfor %}
                    {% endif %}
                </div>
            </div>
            <div class="modal-footer" style="background-color:#F3F6F8;border-radius:6px">
                <br>
                <button type="button" class="btn btn-default cancel-btn" onclick="location.href = '/';">عودة</button>
                <button id='inquire-client-btn' type="button" class="btn btn-primary">استعلام</button>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block js %}
    <script src="{% static 'main/js/new-order.js' %}"></script>

    <script type="text/javascript">
        
        {% if items %}
        var items = {{ items|safe }},
            data = {{ data|safe }};
        
        $('#name, #address, #phone').show();
        
        $('#name').val(data.name);
        $('#address').val(data.address);
        $('#phone').val(data.phone);
        
        $('#inquire-client-btn')
            .attr('id', 'create-order')
            .text('تأكيد')
            .removeClass('btn-primary')
            .addClass('btn-success');
        
        {% endif %}
        
    </script>

{% endblock %}

main/templates/main/order-menu.html
{% extends 'base.html' %}
{% load static %}

{% block title %}القائمة{% endblock %}

{% block css %}
    <link href="{% static 'main/css/order-menu.css' %}" rel="stylesheet">
{% endblock %}

{% block body %}

    {% for type, items in item_packages.items %}
    <div style="margin-bottom:75px">
        <h1 dir="rtl">{{ type }}</h1>

        <div style="display: flex" dir="rtl">
            {% for item in items %}
            <div class="item tool-tip">
                <img class="item-img" src="{{ item.image_url }}">
                <span class="tooltiptext">{{ item.components }}</span>
                <p class="item-name">{{ item.name }}</p>
                <input data-associated-with="{{ item.pk }}" type="text" placeholder="العدد">
            </div>

            {% empty %}
            <h2>لا يوجد أصناف فى هذا القسم</h2>
            {% endfor %}
        </div>
    </div>
    {% endfor %}

    <button class="btn btn-lg btn-success" style="margin-left:40%;margin-bottom:100px" id="proceed">متابعة</button>
{% endblock %}

{% block js %}
    <script src="{% static 'main/js/order-menu.js' %}"></script>

    <script type="text/javascript">
        var REQUEST_DATA = {{ data|safe }};
    </script>

{% endblock %}

main/templates/main/todays_orders.html
{% extends 'base.html' %}
{% load static %}

{% block title %}طلبات اليوم{% endblock %}

{% block body %}
<table id="order-table" class="table table-bordered" dir="rtl" data-item-type='maintenance'>
    
    <thead style="text-align:center">
        <tr>
            <th>م</th>
            <th>الاسم</th>
            <th class="sortable" data-criteria='company'><span class='sort-carat'>&#9660;</span>التليفون</th>
            <th class="sortable" data-criteria='type'><span class='sort-carat'>&#9660;</span>العنوان</th>
            <th class="sortable" data-criteria='date'><span class='sort-carat'>&#9660;</span>الطلب</th>
            <th class="sortable" data-criteria='date'><span class='sort-carat'>&#9660;</span>نوع الطلب</th>
            <th class="sortable" data-criteria='date'><span class='sort-carat'>&#9660;</span>اجمالى الفاتورة</th>
            <th class="sortable" data-criteria='date'><span class='sort-carat'>&#9660;</span>ملاحظات</th>
            <th>حذف</th>
        </tr>
    </thead>
    
    <tbody>
        {% for order in Order.all %}
        <tr data-pk="{{ order.pk }}">
            <td>{{ forloop.counter }}</td>
            <td>{{ order.client.name }}</td>
            <td>{{ order.client.phone }}</td>
            <td>{{ order.client.address }}</td>
            <td><a href='#' data-toggle='modal' data-target='#order-modal' class="order-modal-btn">عرض</a></td>
            <td>{{ order.get_order_type_display }}</td>
            <td>{{ order.total_cost }}</td>
            <td>{{ order.notes }}</td>
            <td><img src="{% static 'images/remove.png' %}" class="icon remove-order-item" data-pk="{{ order.pk }}"></td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<div id='order-modal' class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title people-modal-title">تفاصيل الطلب</h5>
            </div>
            <div class="modal-body" id="order-body" dir="rtl"></div>
            <div class="modal-footer" style="background-color:#F3F6F8;border-radius:6px">
                <br>
                <button type="button" class="btn btn-default cancel-btn" data-dismiss="modal">عودة</button>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block js %}
    <script src="{% static 'main/js/todays-orders.js' %}"></script>

    <script type="text/javascript">
        
        var orders = {{ orders|safe }};
        
    </script>

{% endblock %}